name: ci pipeline

on:
  push:

jobs:
  build:
  
    runs-on: ubuntu-latest
    steps:

      - name: checkout repro
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: install dependes
        run: |
          pip install -r requirements.txt
          pip install dvc
      - name: run dvc pipeline
        env:
          DAGSHUB_PAT:  ${{ secrets.SALARY}}
        run: |
          dvc repro


