name: CI Pipeline

on:
  push:

jobs:
  build:
  
    runs-on: ubuntu-latest
    steps:

      - name: checkout repro
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'


      - name: install dependes
        run: |
          pip install -r requirements.txt
          pip install "dvc[s3]"

      - name: AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}


      - name: dvc pull
        run: |
          dvc pull


      - name: run dvc
        run: |
          dvc repro
     


