name: CI Pipeline

on:
  push:

jobs:
  build:
  
    runs-on: ubuntu-latest
    steps:

      - name: checkout repro
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'


      - name: install dependes
        run: |
          pip install -r requirements.txt


      - name: run dvc
        run: |
          export CI=true
          dvc repro
     


